### ISSUE TITLE
Mod crashes the whole game

### ISSUE THREAD

**Issue by d689** [stacktrace-error/payload-corp#1]
Pls fix
Mindustry has crashed. How unfortunate.
Version: pre-alpha build 135
OS: Linux xnull (aarch64)
Java Version: 0
Mods: payload-corp:[0.1] Added 2 units and factory., test-utils:30

> ArcRuntime: 'java.lang.NullPointerException: Attempt to invoke virtual method 'arc.graphics.Color arc.graphics.Color.set(int)' on a null object reference'
AssetManager.handleTaskError: 670
AssetManager.update: 442
AssetManager.update: 465
ClientLauncher.update: 146
AndroidGraphics.onDrawFrame: 374
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259
> NullPointer: 'Attempt to invoke virtual method 'arc.graphics.Color arc.graphics.Color.set(int)' on a null object reference'
Block.createIcons: 918
Mods.lambda$loadSync$10: 282
Mods.$r8$lambda$XBjcmTlVLflfEWVj2ZacHuW2-sI: -1
Mods$$ExternalSyntheticLambda15.get: -1
Seq.each: 199
Mods.loadSync: 278
AssetManager$2.loadSync: 358
AssetLoadingTask.handleAsyncLoader: 109
AssetLoadingTask.update: 74
AssetManager.updateTask: 591
AssetManager.update: 440
AssetManager.update: 465
ClientLauncher.update: 146
AndroidGraphics.onDrawFrame: 374
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259

**Comment by stacktrace-error** [comment]
that array is completely missing in the current public version, try updating to see if it works
